name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: sudo apt install clang lld && git clone https://github.com/Catcrafts/Crafter.Build.git && cd Crafter.Build && ./build.sh && cd ..
      - name: Build
        run: ./Crafter.Build/bin/crafter-build -c release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bin/crafter-webbuild